<?php

$products = [
    new Toys('Pallina', 10, new Categories('Cane', ' <i class="fa-solid fa-dog fa-bounce" style="color: #1101e9;"></i>'),  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6Uw_q6kNHzyBMfCZlpLGmrZYw7x4plfyqGE_3q--UMJ_zF2xZ6VbC4zD3y4RJu10TdNc&usqp=CAU', 20,'Rotonda', 'Plastica', 'Piccola'), 
    new Accessories('Guinzaglio', 10, new Categories('Cane', ' <i class="fa-solid fa-dog fa-bounce" style="color: #1101e9;"></i>'), 'https://www.delashop.it/wp-content/uploads/2020/06/M_guinzaglioazzurro_picc.jpg',10, 'Resistente', 'Nylon', 'Regolabile'),
    new Food('Crocchetta', 10, new Categories('Cane', ' <i class="fa-solid fa-dog fa-bounce" style="color: #1101e9;"></i>'), 'https://www.petsplanet.it/713-full_default/green-for-dog-crocchette-per-tutti-i-cani-4-kg.jpg',45, 'Senza glutine', 'Nutriente', 'Piccola', '10-12-2024'),
    new Kennel('Cuccia', 10, new Categories('Cane', ' <i class="fa-solid fa-dog fa-bounce" style="color: #1101e9;"></i>'), 'https://www.spesagodina.it/web/wp-content/uploads/2022/03/8410650164076.jpg',22, 'Confortevole', 'Tessuto', 'Grande'),
    new Toys('Palletta', 10, new Categories('Gatto', ' <i class="fa-solid fa-cat fa-bounce" style="color: #de4917;"></i>'), 'https://m.media-amazon.com/images/I/81C56y96syL._AC_SY355_.jpg', '','Rimbalzante', 'Gomma', 'Piccola'),
    new Accessories('Mantello', 10, new Categories('Gatto', ' <i class="fa-solid fa-cat fa-bounce" style="color: #de4917;"></i>'), 'https://thumbs.dreamstime.com/z/gatto-del-supereroe-whiskas-scozzese-con-un-mantello-e-una-maschera-blu-il-concetto-di-eccellente-capo-131186961.jpg','', 'Caldo', 'Pelliccia', 'Regolabile'),
    new Food('Crocchetta', 10, new Categories('Gatto ', '<i class="fa-solid fa-cat fa-bounce" style="color: #de4917;"></i>'), 'https://www.spesagodina.it/web/wp-content/uploads/2022/03/8410650164076.jpg','', 'High Protein', 'Digestibile', 'Piccola', '10-12-2023'),
    new Kennel('Cuscino', 10, new Categories('Gatto', ' <i class="fa-solid fa-cat fa-bounce" style="color: #de4917;"></i>'), 'https://m.media-amazon.com/images/I/71EcMOqPgLL._AC_SY355_.jpg',5, 'Comodo', 'Morbido', 'Medio'),
    new Toys('Topo finto', 10, new Categories('Pesce', ' <i class="fa-solid fa-fish-fins fa-bounce" style="color: #f20202;"></i>'), 'https://shop.ideedecori.com/47086-thickbox_default/eurocarneval-topo-finto-in-gomma-scherzo-topolino-horror-105311.jpg','', 'Movimento realistico', 'Plastica', 'Piccolo'),
    new Accessories('Occhiali', 10, new Categories('Pesce', ' <i class="fa-solid fa-fish-fins fa-bounce" style="color: #f20202;"></i>'), 'https://t1.pixers.pics/img-c676e9e9/quadri-su-tela-Pesce-e-occhiali-da-sole.jpg?H4sIAAAAAAAAA42PTW6EMAyFrwMSGTsJIYQDzHaOgJJgprT8Kcm0qKdvmFbdVaq88LPl91kPHmu0I4GnNVGAZRqGmWCc5jzFLlCcPqnASilVdnk7F4hYdts7BR-2vWAGK6ZkpTRWDeqy-7DZuNjwVryktMcOIMrLPh2ZlpuP4JcIAnkDHEHpkQTH2ipPqt_nLa0bE5qZ-pCKqeayr_cKz_o_uH2C3cBd49oBa9f2QuChkP0SnlgpRU5lTvRPSo1Y6TNdCtNS5Lhbvk7F634v4Y-f3xqyC643EBJMDdqcIq_6601IU2sjZM_JOj2MxrpRk_dNI5VwviXOLVmh_SV_-QI_4s8JiwEAAA==',5, 'Idrorepellente', 'Gomma', 'Piccolo'),
    new Food('Cibo Pesciarolo', 10, new Categories('Pesce ', '<i class="fa-solid fa-fish-fins fa-bounce" style="color: #f20202;"></i>'), 'https://www.aquariumpassion.it/687-large_default/tropical-goldfish-color-gr50ml250-mangime-in-scaglie-per-pesci-rossi.jpg', 49, 'Percarnivori', 'Nutriente', 'piccolo', '4-11-2023'),
    new Kennel('Cuccia inutile', 10, new Categories('Pesce ', '<i class="fa-solid fa-fish-fins fa-bounce" style="color: #f20202;"></i>'), 'https://m.media-amazon.com/images/I/61eBv5UEhRL._AC_SY355_.jpg','', 'Facile da pulire', 'Plastica', 'Piccolo','4434343243', ),
    new Toys('Gatto finto', 10, new Categories('Tartaruga', ' <i class="fa-sharp fa-solid fa-user-ninja fa-bounce" style="color: #1100ff;"></i>'), 'https://www.mio-peluche.it/wp-content/uploads/sites/2/2021/12/morbido-gatto-di-peluche-600x600.jpg',35, 'Galleggiante', 'Gomma', 'Piccolo'),
    new Accessories('Cosa inutile', 10, new Categories('Tartaruga', ' <i class="fa-sharp fa-solid fa-user-ninja fa-bounce" style="color: #1100ff;"></i>'), 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAAaq2aW9-JKg1U46vO5cesPuqyhwQycdP-XljxfkxPIhmPUtE-WarXnOqHmBnHRy3rpw&usqp=CAU','', 'Idrorepellente', 'Gomma', 'Piccolo' ),
    new Food('Cibo tartaruga', 10, new Categories('Tartaruga ', '<i class="fa-sharp fa-solid fa-user-ninja fa-bounce" style="color: #1100ff;"></i>'), 'https://static.zoomalia.com/prod_img/13196/lm_928d045c59a90d7587d8d671b5f5aec4e7c1609745947.jpg', 10,'Per tartarughe acquatiche', 'Nutriente', 'Piccolo', '13-12-2023' ),
    new Kennel('Cuccia strana', 10, new Categories('Tartaruga ', '<i class="fa-sharp fa-solid fa-user-ninja fa-bounce" style="color: #1100ff;"></i>'), 'https://i.ebayimg.com/images/g/UPgAAOSwAnJgAH0K/s-l500.jpg',12, 'Facile da pulire', 'Plastica', 'Piccolo')

];


